<?php

/**
 * Implementation of hook_help().
 */
function onthisdate_help($path, $arg) {
	$output = '';
	switch($path){
		case 'admin/help#seo_link':
		$output = '<p>'.t('Replace the first occurance of a keyword by a link').'</p>';
		break;
	}
	return $output;
}

/**
 * Implementation of hook_perm().
 */
function seo_link_perm() {
  return array('administer SEO Link');
}

/**
 * Implementation of hook_menu().
 */
function seo_link_menu($cache) {

  	$items = array();

    $items['admin/content/seo_link'] = array(
  		'title' => 'SEO Links',
  		'page callback' => 'seo_link_list',
  		'access arguments' => array('administer SEO Link'),
    );

    $items['admin/content/seo_link/list'] = array(
  		'title' => 'List',
    	'type' => MENU_DEFAULT_LOCAL_TASK,
    	'weight' => -10,
    	'access arguments' => array('administer SEO Link'),
	);
	$items['admin/content/seo_link/add'] = array(
	    'title' => 'Add new SEO Link',
	    'page callback' => 'seo_link_item_edit',
	    'type' => MENU_LOCAL_TASK,
	    'access arguments' => array('administer SEO Link'),
	);
	$items['admin/content/seo_link/%/edit'] = array(
		'title' => 'Edit',
		'page callback' => 'seo_link_item_edit',
	    'page arguments' => array(3),
		'type' => MENU_CALLBACK,
		'access arguments' => array('administer SEO Link'),
	);
	$items['admin/content/seo_link/%/delete'] = array(
		'title' => 'Delete',
		'page arguments' => array(3),
		'page callback' => 'seo_link_item_delete',
		'type' => MENU_CALLBACK,
		'access arguments' => array('administer SEO Link'),
	);

  return $items;
	
}


function seo_link_list(){
	$result = db_query('SELECT * FROM {seo_link_item} ORDER BY slid ASC');
  	if ($result) {
    	$headers = array(
      		array('data' => t('Find')),
      		array('data' => t('Replace By')),
      		array('data' => t('Operations'))
    	);
	}

	$rows = array();
	while ($item = db_fetch_array($result)) {
      	$rows[] = array($item['find'], $item['replace_by'], l('edit', 'admin/content/seo_link/'. $item['slid'] .'/edit') .' | '. l('delete', 'admin/content/seo_link/'. $item['slid'] .'/delete'));
    }

    $output = theme('table', $headers, $rows, array('id' => 'seo_link_item_list'));

  return $output;
}


function seo_link_item_edit($slid = NULL) {
  return drupal_get_form('seo_link_item_form', $slid);
}			


function seo_link_item_form($form_state, $slid) {
	$form = array();
	$item = $slid ? db_fetch_array(db_query('SELECT * FROM {seo_link_item} WHERE slid = %d', $slid)) : NULL;
	$form['find'] = array(
	    '#type'          => 'textfield',
	    '#title'         => t('Find'),
	    '#required'      => TRUE,
	    '#default_value' => $item['find'],
	  );
	$form['replace_by'] = array(
	    '#type'          => 'textfield',
	    '#title'         => t('Replace by'),
	    '#required'      => TRUE,
	    '#default_value' => $item['replace_by'],
	    ''
	);
	if ($item) {
	    $form['slid'] = array(
	      '#type'            => 'hidden',
	      '#default_value'   => $item['slid'],
	    );
	}

	$form['submit'] = array(
	    '#type' => 'submit',
	    '#value' => t('Submit Link'),
	);

	return $form;
}


function seo_link_item_form_validate($form, &$form_state) {

	$result = db_result(db_query("SELECT * FROM {seo_link_item} WHERE find = '%s'", $form_state['values']['find']));
  	if ($form_state['values']['replace_by'] == ''){
  		form_set_error('replace_by', t('Please ensure you entered a valid link.'));
  	}
    if($result > 0 && !$form_state['values']['slid']){
    	form_set_error('find', t('This word has already been set. ['.$form_state['values']['find'].']'));
    }
	
}


function seo_link_item_form_submit($form, &$form_state) {

  	$slid = $form_state['values']['slid'] ? $form_state['values']['slid'] : NULL;

  	if (!$slid) {
    	$result = db_query("INSERT INTO {seo_link_item} (find, replace_by) VALUES ('%s', '%s')", $form_state['values']['find'], $form_state['values']['replace_by']);
   	 	$msg = 'New Item created successfuly.';
  	}
  	else {

    	$result = db_query("UPDATE {seo_link_item} SET find = '%s', replace_by = '%s' WHERE slid = %d", $form_state['values']['find'], $form_state['values']['replace_by'], $slid);
    	$msg = 'Item successfuly updated.';
  	}
 	if ($result) {
    	drupal_set_message($msg);
    	drupal_goto('admin/content/seo_link/list');
  	}
}


function seo_link_item_delete($slid) {
  $result = db_query('DELETE FROM {seo_link_item} WHERE slid = %d', $slid);
  drupal_set_message('Item #'.$slid.' has been successfuly deleted.');
  drupal_goto('admin/content/seo_link');
}


function seo_link_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
	$result = db_query("SELECT * FROM {seo_link_item}");
	$newContent = $node->content['body']['#value'];
	while($word = db_fetch_object($result)){
		$newContent = str_replace_first($word->find, $word->replace_by, $newContent);
	}
    switch ($op) {
	    case 'view':
	    	$node->content['body']['#value'] = $newContent;
	        break;
    }
}

function str_replace_first($search, $replace, $subject) {
	$search = '/'.$search.'/i';
    return preg_replace($search, $replace, $subject, 1);
}